// USER
export const SET_HEADER_TITLE = "SET_HEADER_TITLE";
export const SET_JOINED_PARAM = "SET_JOINED_PARAM";
export const SET_TRANSFER_PARAM = "SET_TRANSFER_PARAM";
export const SET_PARTY_LIST = "SET_PARTY_LIST";
export const SET_BLACK_THEME = "SET_BLACK_THEME";
export const SET_BALANCE = "SET_BALANCE";
